version: '3'
services:
  hub:
    image: selenium/hub:4.23.0
  chrome:
    image: selenium/node-chrome:127.0
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 1
    env_file: .env
  firefox:
    image: selenium/node-firefox:128.0
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 1
    env_file: .env